(define (pascal row index)
  (cond
    ((= row 0) 1)
    ((= row 1) 1)
    ((= index 0) 1)
    ((= index row) 1)     ; is last item on row?
    (else (+ (pascal (- row 1) (- index 1))
             (pascal (- row 1) index)))
  )
)

(print-and-eval (pascal 0 0))
(print-and-eval (pascal 1 0))
(print-and-eval (pascal 1 1))
(print-and-eval (pascal 2 0))
(print-and-eval (pascal 2 1))
(print-and-eval (pascal 2 2))
(print-and-eval (pascal 3 0))
(print-and-eval (pascal 3 1))
(print-and-eval (pascal 3 2))
(print-and-eval (pascal 3 3))
(print-and-eval (pascal 4 0))
(print-and-eval (pascal 4 1))
(print-and-eval (pascal 4 2))
(print-and-eval (pascal 4 3))
(print-and-eval (pascal 4 4))
